FROM php:7.4.8-fpm-alpine

ENV WPCLI_BIN /usr/local/bin/wp
ENV WPCLI_VERSION 2.4.0
ENV WPCLI_CHECKSUM 4049c7e45e14276a70a41c3b0864be7a6a8cfa8ea65ebac8b184a4f503a91baa1a0d29260d03248bc74aef70729824330fb6b396336172a624332e16f64e37ef
ENV PAGER less -R

RUN wget -q -O ${WPCLI_BIN} https://github.com/wp-cli/wp-cli/releases/download/v${WPCLI_VERSION}/wp-cli-${WPCLI_VERSION}.phar && \
    echo "${WPCLI_CHECKSUM}  ${WPCLI_BIN}" | sha512sum -c && chmod +x ${WPCLI_BIN}

RUN docker-php-ext-install mysqli

COPY ./deploy/files/php/php.ini /usr/local/etc/php/php.ini
COPY ./deploy/files/php/php-fpm.conf /usr/local/etc/php-fpm.conf

USER www-data
